// @ts-nocheck
/**
 * Edge-cron прогрева global_daily_content.
 *
 * С версии prompt v6 этот крон пишет ТОЛЬКО детерминированную structural-строку
 * (планеты, лепестки, math_level) с fallback-текстами и llm_model = null.
 * Настоящие LLM-тексты под v6-промпт генерирует Node-путь
 * `_legacy_web/app/api/_utils/ensureGlobalDailyContent.ts` (через
 * `POST /api/ai/global-content`) при первом заходе free-пользователя —
 * `globalContentNeedsRefresh` остаётся true (llm_model = null), и строка
 * самозалечивается. Это разгружает крон от LLM-вызовов и держит тексты под
 * единым v6-промптом, который собирается в Node-окружении (данные baseline,
 * author voice и т.д. живут в _legacy_web).
 */
import { assertCronSecret, createServiceClient, isOptions, json } from "../_shared/supabase.ts";
import { buildGlobalMathLevel, computeGlobalDailyForecast, GLOBAL_MATH_SCHEMA_VERSION } from "../_shared/dailyForecast.ts";

const GLOBAL_FALLBACK_SLOGAN = "День приглашает настроиться и двигаться в своём темпе.";
const GLOBAL_FALLBACK_SHORT_TEXT =
  "Сегодня полезно удерживать внимание на теле и дыхании, не форсируя решения.";
const GLOBAL_FALLBACK_LONG_EXPLANATION =
  "Транзитная картина дня собрана из положений семи классических планет; развёрнутый текст временно короткий — обновите экран позже.";

function isoDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setUTCDate(result.getUTCDate() + days);
  return result;
}

function calcExpiresAt(forecastDateUtc: string): string {
  const date = new Date(`${forecastDateUtc}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + 1);
  date.setUTCHours(14, 0, 0, 0);
  return date.toISOString();
}

async function writeStructuralRowForDate(db: any, date: string) {
  const forecast = computeGlobalDailyForecast(date);
  const mathLevel = buildGlobalMathLevel(forecast);

  const row = {
    forecast_date_utc: date,
    planet_positions: forecast.planet_positions,
    primary_planet: forecast.primary_planet,
    primary_chakra_number: forecast.primary_chakra_number,
    primary_tone: forecast.primary_tone,
    top_petals: forecast.top_petals,
    slogan: GLOBAL_FALLBACK_SLOGAN,
    short_text: GLOBAL_FALLBACK_SHORT_TEXT,
    long_explanation: GLOBAL_FALLBACK_LONG_EXPLANATION,
    math_level: mathLevel,
    generated_at: new Date().toISOString(),
    llm_tokens_used: null as number | null,
    llm_model: null,
    expires_at_utc: calcExpiresAt(date),
  };

  const { error } = await db.from("global_daily_content").upsert(row, {
    onConflict: "forecast_date_utc",
  });
  if (error) throw error;

  return { date, status: "structural_written" };
}

Deno.serve(async (req) => {
  if (isOptions(req)) return new Response("ok");
  const unauthorized = assertCronSecret(req);
  if (unauthorized) return unauthorized;

  try {
    const db = createServiceClient();
    const now = new Date();
    const dates = [isoDate(addDays(now, -1)), isoDate(now), isoDate(addDays(now, 1))];
    const results = [];

    for (const date of dates) {
      try {
        results.push(await writeStructuralRowForDate(db, date));
      } catch (error) {
        console.error("[precompute-global-recommendations] date failed", date, error);
        results.push({ date, status: "error", error: error instanceof Error ? error.message : String(error) });
      }
    }

    await db.from("global_daily_content").delete().lt("expires_at_utc", new Date().toISOString());

    return json({
      ok: true,
      results,
      note: "structural-only since prompt v6; LLM texts are generated by Node /api/ai/global-content on demand",
    });
  } catch (error) {
    console.error("[precompute-global-recommendations]", error);
    return json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
});
