/** Server-side vendored entry — types only. Generated by scripts/sync-vercel-server-modules.mjs */
export type { BreathPracticeId, BreathLocale } from "@/modules/breath/i18n/coherence";
export type { Chakra } from "@/modules/breath/core/chakra";
