/** AUTO-GENERATED by scripts/i18n-sync.mjs — do not edit by hand. */
import home_de from "./catalog/home/de.json";
import home_es from "./catalog/home/es.json";
import home_fr from "./catalog/home/fr.json";
import home_it from "./catalog/home/it.json";
import home_nl from "./catalog/home/nl.json";
import home_pt from "./catalog/home/pt.json";
import profile_de from "./catalog/profile/de.json";
import profile_es from "./catalog/profile/es.json";
import profile_fr from "./catalog/profile/fr.json";
import profile_it from "./catalog/profile/it.json";
import profile_nl from "./catalog/profile/nl.json";
import profile_pt from "./catalog/profile/pt.json";
import day_de from "./catalog/day/de.json";
import day_es from "./catalog/day/es.json";
import day_fr from "./catalog/day/fr.json";
import day_it from "./catalog/day/it.json";
import day_nl from "./catalog/day/nl.json";
import day_pt from "./catalog/day/pt.json";
import practices_de from "./catalog/practices/de.json";
import practices_es from "./catalog/practices/es.json";
import practices_fr from "./catalog/practices/fr.json";
import practices_it from "./catalog/practices/it.json";
import practices_nl from "./catalog/practices/nl.json";
import practices_pt from "./catalog/practices/pt.json";
import communicator_de from "./catalog/communicator/de.json";
import communicator_es from "./catalog/communicator/es.json";
import communicator_fr from "./catalog/communicator/fr.json";
import communicator_it from "./catalog/communicator/it.json";
import communicator_nl from "./catalog/communicator/nl.json";
import communicator_pt from "./catalog/communicator/pt.json";
import breath_de from "./catalog/breath/de.json";
import breath_es from "./catalog/breath/es.json";
import breath_fr from "./catalog/breath/fr.json";
import breath_it from "./catalog/breath/it.json";
import breath_nl from "./catalog/breath/nl.json";
import breath_pt from "./catalog/breath/pt.json";
import mandala_de from "./catalog/mandala/de.json";
import mandala_es from "./catalog/mandala/es.json";
import mandala_fr from "./catalog/mandala/fr.json";
import mandala_it from "./catalog/mandala/it.json";
import mandala_nl from "./catalog/mandala/nl.json";
import mandala_pt from "./catalog/mandala/pt.json";
import userErrors_de from "./catalog/userErrors/de.json";
import userErrors_es from "./catalog/userErrors/es.json";
import userErrors_fr from "./catalog/userErrors/fr.json";
import userErrors_it from "./catalog/userErrors/it.json";
import userErrors_nl from "./catalog/userErrors/nl.json";
import userErrors_pt from "./catalog/userErrors/pt.json";
import chakra_de from "./catalog/chakra/de.json";
import chakra_es from "./catalog/chakra/es.json";
import chakra_fr from "./catalog/chakra/fr.json";
import chakra_it from "./catalog/chakra/it.json";
import chakra_nl from "./catalog/chakra/nl.json";
import chakra_pt from "./catalog/chakra/pt.json";
import charts_de from "./catalog/charts/de.json";
import charts_es from "./catalog/charts/es.json";
import charts_fr from "./catalog/charts/fr.json";
import charts_it from "./catalog/charts/it.json";
import charts_nl from "./catalog/charts/nl.json";
import charts_pt from "./catalog/charts/pt.json";

export const GENERATED_TYPED_OVERLAYS: Record<
  string,
  Partial<Record<string, Record<string, unknown>>>
> = {
  home: {
    de: home_de as Record<string, unknown>,
    es: home_es as Record<string, unknown>,
    fr: home_fr as Record<string, unknown>,
    it: home_it as Record<string, unknown>,
    nl: home_nl as Record<string, unknown>,
    pt: home_pt as Record<string, unknown>,
  },
  profile: {
    de: profile_de as Record<string, unknown>,
    es: profile_es as Record<string, unknown>,
    fr: profile_fr as Record<string, unknown>,
    it: profile_it as Record<string, unknown>,
    nl: profile_nl as Record<string, unknown>,
    pt: profile_pt as Record<string, unknown>,
  },
  day: {
    de: day_de as Record<string, unknown>,
    es: day_es as Record<string, unknown>,
    fr: day_fr as Record<string, unknown>,
    it: day_it as Record<string, unknown>,
    nl: day_nl as Record<string, unknown>,
    pt: day_pt as Record<string, unknown>,
  },
  practices: {
    de: practices_de as Record<string, unknown>,
    es: practices_es as Record<string, unknown>,
    fr: practices_fr as Record<string, unknown>,
    it: practices_it as Record<string, unknown>,
    nl: practices_nl as Record<string, unknown>,
    pt: practices_pt as Record<string, unknown>,
  },
  communicator: {
    de: communicator_de as Record<string, unknown>,
    es: communicator_es as Record<string, unknown>,
    fr: communicator_fr as Record<string, unknown>,
    it: communicator_it as Record<string, unknown>,
    nl: communicator_nl as Record<string, unknown>,
    pt: communicator_pt as Record<string, unknown>,
  },
  breath: {
    de: breath_de as Record<string, unknown>,
    es: breath_es as Record<string, unknown>,
    fr: breath_fr as Record<string, unknown>,
    it: breath_it as Record<string, unknown>,
    nl: breath_nl as Record<string, unknown>,
    pt: breath_pt as Record<string, unknown>,
  },
  mandala: {
    de: mandala_de as Record<string, unknown>,
    es: mandala_es as Record<string, unknown>,
    fr: mandala_fr as Record<string, unknown>,
    it: mandala_it as Record<string, unknown>,
    nl: mandala_nl as Record<string, unknown>,
    pt: mandala_pt as Record<string, unknown>,
  },
  userErrors: {
    de: userErrors_de as Record<string, unknown>,
    es: userErrors_es as Record<string, unknown>,
    fr: userErrors_fr as Record<string, unknown>,
    it: userErrors_it as Record<string, unknown>,
    nl: userErrors_nl as Record<string, unknown>,
    pt: userErrors_pt as Record<string, unknown>,
  },
  chakra: {
    de: chakra_de as Record<string, unknown>,
    es: chakra_es as Record<string, unknown>,
    fr: chakra_fr as Record<string, unknown>,
    it: chakra_it as Record<string, unknown>,
    nl: chakra_nl as Record<string, unknown>,
    pt: chakra_pt as Record<string, unknown>,
  },
  charts: {
    de: charts_de as Record<string, unknown>,
    es: charts_es as Record<string, unknown>,
    fr: charts_fr as Record<string, unknown>,
    it: charts_it as Record<string, unknown>,
    nl: charts_nl as Record<string, unknown>,
    pt: charts_pt as Record<string, unknown>,
  },
};
