/** Короткие русские названия ISO-3166-1 alpha-2 для админ-отчётов. */
const COUNTRY_NAMES_RU: Record<string, string> = {
  RU: "Россия",
  US: "США",
  DE: "Германия",
  FR: "Франция",
  IT: "Италия",
  ES: "Испания",
  PT: "Португалия",
  NL: "Нидерланды",
  GB: "Великобритания",
  UA: "Украина",
  BY: "Беларусь",
  KZ: "Казахстан",
  UZ: "Узбекистан",
  TR: "Турция",
  PL: "Польша",
  CZ: "Чехия",
  AT: "Австрия",
  CH: "Швейцария",
  SE: "Швеция",
  NO: "Норвегия",
  FI: "Финляндия",
  DK: "Дания",
  BE: "Бельгия",
  IE: "Ирландия",
  CA: "Канада",
  AU: "Австралия",
  BR: "Бразилия",
  MX: "Мексика",
  AR: "Аргентина",
  IN: "Индия",
  CN: "Китай",
  JP: "Япония",
  KR: "Корея",
  IL: "Израиль",
  AE: "ОАЭ",
  GE: "Грузия",
  AM: "Армения",
  AZ: "Азербайджан",
  MD: "Молдова",
  LV: "Латвия",
  LT: "Литва",
  EE: "Эстония",
};

export function countryNameRu(code: string | null | undefined): string {
  if (!code) return "Не указано";
  const key = code.trim().toUpperCase();
  return COUNTRY_NAMES_RU[key] ?? key;
}
