#!/usr/bin/env bash
# sync-web-env.sh — derives _legacy_web/.env.local from the root .env.local.
#
# WHY two files exist:
#   Root .env.local  = Expo (React Native) source of truth. Uses EXPO_PUBLIC_* prefixes.
#   _legacy_web/.env.local = Next.js server. Uses NEXT_PUBLIC_* for browser-visible vars.
#
# This script:
#   1. Translates EXPO_PUBLIC_SUPABASE_URL → NEXT_PUBLIC_SUPABASE_URL
#      and EXPO_PUBLIC_SUPABASE_ANON_KEY → NEXT_PUBLIC_SUPABASE_ANON_KEY
#   2. Copies every shared server-side variable (AI models, secrets, API keys…)
#   3. Drops Expo-only, dev-tool-only, and Supabase-CLI-only vars.
#
# Usage:  ./scripts/sync-web-env.sh
# Hooked: .git/hooks/pre-commit (auto-installed by install.sh)

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_ENV="$REPO_ROOT/.env.local"
WEB_ENV="$REPO_ROOT/_legacy_web/.env.local"

if [ ! -f "$ROOT_ENV" ]; then
  echo "⚠️  sync-web-env: $ROOT_ENV not found — skipping" >&2
  exit 0
fi

# ── Vars to SKIP from root (Expo-only, dev-tools, Supabase CLI) ──────────────
# These are never read by the Next.js process.
SKIP_PATTERNS=(
  "^EXPO_PUBLIC_"           # Expo client bundle vars
  "^NGROK_AUTHTOKEN="
  "^CURSOR_API_KEY="
  "^SUPABASE_PROJECT_REF="
  "^SUPABASE_DB_PASSWORD="
  "^SUPABASE_DB_URL="
  "^SUPABASE_URL="          # Supabase CLI; Next.js uses NEXT_PUBLIC_SUPABASE_URL
)

# Build a single grep -E pattern from the skip list
SKIP_RE=$(printf "|%s" "${SKIP_PATTERNS[@]}")
SKIP_RE="${SKIP_RE:1}"  # remove leading |

# ── Translate EXPO_PUBLIC_SUPABASE_* → NEXT_PUBLIC_SUPABASE_* ────────────────
SUPABASE_URL=$(grep  "^EXPO_PUBLIC_SUPABASE_URL="       "$ROOT_ENV" | head -1 | cut -d'=' -f2-)
SUPABASE_KEY=$(grep  "^EXPO_PUBLIC_SUPABASE_ANON_KEY="  "$ROOT_ENV" | head -1 | cut -d'=' -f2-)

# ── Write _legacy_web/.env.local ─────────────────────────────────────────────
{
  echo "# AUTO-GENERATED — edit .env.local in the repo root, then run scripts/sync-web-env.sh"
  echo "# Do NOT edit this file directly."
  echo ""
  echo "# Supabase (Next.js requires NEXT_PUBLIC_* for browser-visible vars)"
  echo "NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_KEY"
  echo ""
  echo "# Shared server-side vars (copied from root .env.local)"
  grep -vE "$SKIP_RE" "$ROOT_ENV" \
    | grep -v "^#" \
    | grep -v "^[[:space:]]*$"
} > "$WEB_ENV"

echo "✓ _legacy_web/.env.local synced from .env.local"
