/** AUTO-GENERATED by scripts/sync-vercel-server-modules.mjs — server API slice only. */
import breath_de from "./catalog/breath/de.json";
import breath_es from "./catalog/breath/es.json";
import breath_fr from "./catalog/breath/fr.json";
import breath_it from "./catalog/breath/it.json";
import breath_nl from "./catalog/breath/nl.json";
import breath_pt from "./catalog/breath/pt.json";
import day_de from "./catalog/day/de.json";
import day_es from "./catalog/day/es.json";
import day_fr from "./catalog/day/fr.json";
import day_it from "./catalog/day/it.json";
import day_nl from "./catalog/day/nl.json";
import day_pt from "./catalog/day/pt.json";
import practices_de from "./catalog/practices/de.json";
import practices_es from "./catalog/practices/es.json";
import practices_fr from "./catalog/practices/fr.json";
import practices_it from "./catalog/practices/it.json";
import practices_nl from "./catalog/practices/nl.json";
import practices_pt from "./catalog/practices/pt.json";

export const GENERATED_TYPED_OVERLAYS: Record<
  string,
  Partial<Record<string, Record<string, unknown>>>
> = {
  breath: {
    de: breath_de as Record<string, unknown>,
    es: breath_es as Record<string, unknown>,
    fr: breath_fr as Record<string, unknown>,
    it: breath_it as Record<string, unknown>,
    nl: breath_nl as Record<string, unknown>,
    pt: breath_pt as Record<string, unknown>,
  },
  day: {
    de: day_de as Record<string, unknown>,
    es: day_es as Record<string, unknown>,
    fr: day_fr as Record<string, unknown>,
    it: day_it as Record<string, unknown>,
    nl: day_nl as Record<string, unknown>,
    pt: day_pt as Record<string, unknown>,
  },
  practices: {
    de: practices_de as Record<string, unknown>,
    es: practices_es as Record<string, unknown>,
    fr: practices_fr as Record<string, unknown>,
    it: practices_it as Record<string, unknown>,
    nl: practices_nl as Record<string, unknown>,
    pt: practices_pt as Record<string, unknown>,
  },
};
